export function generateReadme(project: any, estimation: any): string {
    const tasks = typeof estimation.tasks === 'string'
        ? JSON.parse(estimation.tasks)
        : estimation.tasks || [];

    const totalHours = estimation.totalHours || 0;
    const estCost = estimation.cost ? `$${estimation.cost}` : 'N/A';

    // Fallback if no specific tech stack in DB yet, but we can assume some defaults or placeholdesr
    const techStack = project.techStack || ['Next.js', 'React', 'TypeScript', 'Prisma'];

    let taskListMd = '';

    // Helper to recursively print tasks
    const printTasks = (items: any[], depth: number = 0) => {
        let output = '';
        const indent = '  '.repeat(depth);
        items.forEach((task: any) => {
            output += `${indent}- ${task.title} (${task.hours}h)\n`;
            if (task.subtasks && task.subtasks.length > 0) {
                output += printTasks(task.subtasks, depth + 1);
            }
        });
        return output;
    };

    taskListMd = printTasks(tasks);

    return `# ${project.name}

> Generated by **AI Estimation**

## 📋 Overview
${project.description || 'No description provided.'}

## 🏗️ Technical Stack
${techStack.map((tech: string) => `- ${tech}`).join('\n')}

## ⏱️ Estimation Summary
- **Total Estimated Hours**: ${totalHours} hours
- **Estimated Cost**: ${estCost}

## 📝 Task Breakdown
${taskListMd}

---
*This README was automatically generated based on the estimation created on ${new Date().toLocaleDateString()}.*
`;
}
